### ISSUE TITLE
lack of arduino settings 

### ISSUE THREAD

**Issue by nemo1966** [pcktdmp/teensy-3.1-snespad#1]
No arduino settings? e.g 48, 72, 96MHz

What OS is it good for? Windows , android, linux?

Seems to lack debounce.

**Comment by pcktdmp** [comment]
Hi nemo1966,

This code is only made for the Teensy 3.1 with 'teensyduino' (https://www.pjrc.com/teensy/teensyduino.html).
When you are in the Arduino IDE you need to switch to 'Board -> Teensy 3.1' and 'USB Type -> Keyboard + Mouse + Joystick'

I guess it doesn't need debounce since the controllers sends an internal state (which buttons are currently pressed) continuously instead of individual button presses, emulators like it that way.
Also the library that needs to be installed (SNESpad.h) handles read timings of the button states. https://code.google.com/p/nespad/downloads/list

It should work for any OS that handles generic gamepads, I tested it for Linux and Mac OSX with board on 96Mhz

**Comment by pcktdmp** [comment]
PS
It should work for any OS that handles generic gamepads, I tested it for Linux and Mac OSX.

**Comment by nemo1966** [comment]
Thank you, great information,  I will give it a try on Android and let you know how it goes. I've had problems with Teensy 3.1 with Android in the past with the standard keyboard - mouse - joystick libs. Many have had to strip out the Mouse - keyboard parts and leave just the joysticks section in place for it to work.

Again, thanks for the reply and effort - appreciated.

**Comment by nemo1966** [comment]
As suspected, works sporadically on Android 4.4.2 and cannot get the gamepad/Hat working at all. Works fine on Win7. A lot of people have had this problem, the only way to get it to work properly is to directly edit the USB core files which isn't ideal.

**Comment by nemo1966** [comment]
TBH after many hours of fiddling - the Teensy 2.0 using https://github.com/jjstreet/teensyarcade has the best compatibility will all OS'es

**Comment by pcktdmp** [comment]
Hi nemo1966,

Hmm, if only I had an Android device I could reproduce the problem, what kind of software/game are you trying to work with? It could be that the 'generic joypad' teensyduino isn't that generic :-)

**Comment by nemo1966** [comment]
You may very well be right, have a look at http://hamaluik.com/tag/teensy3/ its for teensy 3.0 but works with 3.1 this works with win7 and android. 

The games are snes9x emulator and the mame4droid. Basically old school emulators, I was around when the consoles first came out. Super Mario Bros 1 and 3, space Invaders are still some of the best games ever made imho.  Although when I was a kid I had a pong and was the first in our school to get the Atari 2600... great days lol
